/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dashboard.CUSTOMER;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class CUSTOMER_DUE extends javax.swing.JPanel {

    /**
     * Creates new form CUSTOMER_DUE
     */
    public CUSTOMER_DUE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        CUSTOMERDUPHNO = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        BALANCEAMOUNT = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        SALESID = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CURRENTAMOUNT = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        NETAMOUNT = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Customer Due");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(691, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setFont(new java.awt.Font("STIXNonUnicode", 2, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "salesid", "CUSID", "CUSTOMERNAME", "CUSTOMERPH", "TOTALQTY", "TOTALITEMS", "PAYMODE", "BALANCEAMOUNT", "CURRENTAMOUNT", "NETAMOUNT", "DATE"
            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 940, 290));

        jLabel3.setText("PHONE NUMBER");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, 30));

        CUSTOMERDUPHNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CUSTOMERDUPHNOActionPerformed(evt);
            }
        });
        jPanel1.add(CUSTOMERDUPHNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 150, 30));

        jLabel2.setText("BALANCEAMOUNT");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 130, -1));
        jPanel1.add(BALANCEAMOUNT, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 140, 30));

        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, -1, -1));

        jLabel4.setText("SALESID");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        SALESID.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(SALESID, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 50, 20));

        jLabel5.setText("CURRENTAMOUNT");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 340, -1, 20));
        jPanel1.add(CURRENTAMOUNT, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 340, 160, -1));

        jLabel6.setText("NETAMOUNT");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, -1, -1));
        jPanel1.add(NETAMOUNT, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 130, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 980, 460));
    }// </editor-fold>//GEN-END:initComponents

    private void CUSTOMERDUPHNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CUSTOMERDUPHNOActionPerformed
  int c;
        try {
     
        
       con1=DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql?zeroDateTimeBehavior=convertToNull","root","root@123");
  insert=con1.prepareStatement("SELECT * FROM trade.CUSTOMERDUE where CUSTOMERPH=?");
  insert.setString(1,CUSTOMERDUPHNO.getText());
  ResultSet rs=insert.executeQuery();
   ResultSetMetaData Rss=rs.getMetaData();
 c=Rss.getColumnCount();
 
    DefaultTableModel df=(DefaultTableModel)jTable1.getModel();
    df.setRowCount(0);
    while(rs.next())
    {
        Vector v2=new Vector();
        for(int a=0;a<=c;a++)
        {
            
            v2.add(rs.getString("salesid"));
            v2.add(rs.getString("CUSID"));
            v2.add(rs.getString("customername"));
            v2.add(rs.getString("CUSTOMERPh"));
            v2.add(rs.getString("totalqty"));
            v2.add(rs.getString("totalitems"));
            v2.add(rs.getString("paymode"));
            v2.add(rs.getString("balanceamount"));
            v2.add(rs.getString("currentamount"));
            v2.add(rs.getString("netamount"));
            v2.add(rs.getString("DATE"));
            
            
            
        }
        df.addRow(v2);
    }
  
       
      } 
      catch (SQLException ex) {
            Logger.getLogger(CUSTOMER_DUE.class.getName()).log(Level.SEVERE, null, ex);
        }
    
        
        
    }//GEN-LAST:event_CUSTOMERDUPHNOActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel df=(DefaultTableModel)jTable1.getModel();
    
        int selectedIndex=jTable1.getSelectedRow();
      SALESID.setText(df.getValueAt(selectedIndex, 0).toString()) ; 
     BALANCEAMOUNT.setText(df.getValueAt(selectedIndex,7).toString());
   CURRENTAMOUNT.setText(df.getValueAt(selectedIndex,8).toString());
    NETAMOUNT.setText(df.getValueAt(selectedIndex, 9).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       DefaultTableModel df=(DefaultTableModel)jTable1.getModel();
        int selectedIndex=jTable1.getSelectedRow();
    
         try {
           int Id=Integer.parseInt((df.getValueAt(selectedIndex, 0).toString()));
        int salesid=Integer.parseInt(SALESID.getText());
          String balanceamount=BALANCEAMOUNT.getText();
        String currentamount=CURRENTAMOUNT.getText();
        String netamount=NETAMOUNT.getText();
       
        
       con1=DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql?zeroDateTimeBehavior=convertToNull","root","root@123");
  insert=con1.prepareStatement("update trade.CUSTOMERDUE set salesid=?,BALANCEAMOUNT=?, CURRENTAMOUNT=?, NETAMOUNT=? where salesid=?");
   insert.setInt(1, salesid);
  insert.setString(2, balanceamount);
      insert.setString(3, currentamount);
      insert.setString(4, netamount);
        insert.setInt(5, Id);
        
      insert.executeUpdate();
        
      } 
      catch (SQLException ex) {
            Logger.getLogger(CUSTOMER_DUE.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

Connection con1;
PreparedStatement insert;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BALANCEAMOUNT;
    private javax.swing.JTextField CURRENTAMOUNT;
    private javax.swing.JTextField CUSTOMERDUPHNO;
    private javax.swing.JTextField NETAMOUNT;
    private javax.swing.JLabel SALESID;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
