/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dashboard;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class ADDPRODUCt extends javax.swing.JPanel {

    /**
     * Creates new form ADDPRODUCt
     */
    public ADDPRODUCt() {
        initComponents();
  tb_load1();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        QTY = new javax.swing.JTextField();
        CategoryName = new javax.swing.JTextField();
        BrandName = new javax.swing.JTextField();
        ProductName = new javax.swing.JTextField();
        WholeSaleRate = new javax.swing.JTextField();
        TotalAmount = new javax.swing.JTextField();
        MRP = new javax.swing.JTextField();
        JADD = new javax.swing.JButton();
        JUPDATE = new javax.swing.JButton();
        JDELETE = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ADD PRODUCT");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(644, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 940, 70));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Brand Name");

        jLabel3.setText("QTY");

        jLabel4.setText("Product Name");

        jLabel5.setText("Category Name");

        jLabel6.setText("MRP");

        jLabel7.setText("WholeSale Rate");

        jLabel8.setText("Total Amount");

        JADD.setBackground(new java.awt.Color(0, 51, 153));
        JADD.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        JADD.setForeground(new java.awt.Color(255, 255, 255));
        JADD.setText("ADD");
        JADD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JADDActionPerformed(evt);
            }
        });

        JUPDATE.setBackground(new java.awt.Color(0, 51, 153));
        JUPDATE.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        JUPDATE.setForeground(new java.awt.Color(255, 255, 255));
        JUPDATE.setText("Update");
        JUPDATE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JUPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JUPDATEActionPerformed(evt);
            }
        });

        JDELETE.setBackground(new java.awt.Color(0, 0, 153));
        JDELETE.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        JDELETE.setForeground(new java.awt.Color(255, 255, 255));
        JDELETE.setText("Delete");
        JDELETE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JDELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JDELETEActionPerformed(evt);
            }
        });

        jScrollPane1.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setFont(new java.awt.Font("STIXNonUnicode", 2, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Product Name", "Brand Name", "Category Name", "QTY", "MRP", "WholeSale Rate", "TotalAmount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setColumnSelectionAllowed(true);
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(JADD, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JUPDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JDELETE, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(137, 137, 137))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CategoryName, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BrandName, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(65, 65, 65)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MRP, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(QTY, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(24, 24, 24)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(WholeSaleRate, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QTY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BrandName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MRP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CategoryName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WholeSaleRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JADD, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JUPDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JDELETE, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 940, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents
Connection con1;
PreparedStatement insert;


  private void tb_load1(){
  int c;
  try{
           con1=DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql?zeroDateTimeBehavior=convertToNull","root","root@123");
 insert=con1.prepareStatement("SELECT * FROM Trade.ADDPRODUCt");
 ResultSet re=insert.executeQuery();
 ResultSetMetaData Rss=re.getMetaData();
 c=Rss.getColumnCount();
 
    DefaultTableModel df=(DefaultTableModel)jTable1.getModel();
    df.setRowCount(0);
    while(re.next())
    {
        Vector v2=new Vector();
        for(int a=0;a<=c;a++)
        {
            v2.add(re.getString("Id"));
            v2.add(re.getString("Productname"));
            v2.add(re.getString("Brandname"));
            v2.add(re.getString("Categoryname"));
            v2.add(re.getString("Qty"));
            v2.add(re.getString("Mrp"));
            v2.add(re.getString("Wholesalerate"));
            v2.add(re.getString("Totalamount"));
            
            
        }
        df.addRow(v2);
    }
    
  }
  catch(SQLException ex)
  {
           Logger.getLogger(ADDPRODUCt.class.getName()).log(Level.SEVERE, null, ex);
       
  }
  
  
  } 
    private void JADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JADDActionPerformed
        // insert the product Record
        String Productname=ProductName.getText();
        String Brandname=BrandName.getText();
        String Categoryname=CategoryName.getText();
        String Qty=QTY.getText();
        String Mrp=MRP.getText();
        String Wholesalerate=WholeSaleRate.getText();
        String Totalamount=TotalAmount.getText();

      try {
       con1=DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql?zeroDateTimeBehavior=convertToNull","root","root@123");
  insert=con1.prepareStatement("INSERT INTO Trade.ADDPRODUCt (PRODUCTNAMe, BRANDNAMe, CATEGORYNAMe, QTy, MRp, WHOLESALERATe, TOTALAMOUNt)VALUES (?, ?, ?, ?, ?, ?, ?)");
      insert.setString(1, Productname);
      insert.setString(2, Brandname);
      insert.setString(3, Categoryname);
      insert.setString(4, Qty);
      insert.setString(5, Mrp);
      insert.setString(6, Wholesalerate);
      insert.setString(7, Totalamount);
      insert.executeUpdate();
         tb_load1();
       ProductName.setText("");
       BrandName.setText("");
       CategoryName.setText("");
       QTY.setText("");
       MRP.setText("");
        WholeSaleRate.setText("");
        TotalAmount.setText("");
        ProductName.requestFocus(); 
      } 
      catch (SQLException ex) {
            Logger.getLogger(ADDPRODUCt.class.getName()).log(Level.SEVERE, null, ex);
        }
     
    }//GEN-LAST:event_JADDActionPerformed

    private void JUPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JUPDATEActionPerformed
        // Update the product
        
    DefaultTableModel df=(DefaultTableModel)jTable1.getModel();
        int selectedIndex=jTable1.getSelectedRow();
    
         try {
             int ID=Integer.parseInt(df.getValueAt(selectedIndex, 0).toString());
        
             String Productname=ProductName.getText();
        String Brandname=BrandName.getText();
        String Categoryname=CategoryName.getText();
        String Qty=QTY.getText();
        String Mrp=MRP.getText();
        String Wholesalerate=WholeSaleRate.getText();
        String Totalamount=TotalAmount.getText();
        
       con1=DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql?zeroDateTimeBehavior=convertToNull","root","root@123");
  insert=con1.prepareStatement("update Trade.ADDPRODUCt set PRODUCTNAMe=?, BRANDNAMe=?, CATEGORYNAMe=?, QTy=?, MRp=?, WHOLESALERATe=?, TOTALAMOUNt=? where Id=?");
       
      insert.setString(1, Productname);
      insert.setString(2, Brandname);
      insert.setString(3, Categoryname);
      insert.setString(4, Qty);
      insert.setString(5, Mrp);
      insert.setString(6, Wholesalerate);
      insert.setString(7, Totalamount);
       insert.setInt(8,ID); 
      insert.executeUpdate();
         tb_load1();
       ProductName.setText("");
       BrandName.setText("");
       CategoryName.setText("");
       QTY.setText("");
       MRP.setText("");
        WholeSaleRate.setText("");
        TotalAmount.setText("");
        ProductName.requestFocus(); 
      } 
      catch (SQLException ex) {
            Logger.getLogger(ADDPRODUCt.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_JUPDATEActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:  
    DefaultTableModel df=(DefaultTableModel)jTable1.getModel();
    
        int selectedIndex=jTable1.getSelectedRow();
        
     ProductName.setText(df.getValueAt(selectedIndex,1).toString());
     BrandName.setText(df.getValueAt(selectedIndex,2).toString());
     CategoryName.setText(df.getValueAt(selectedIndex,3).toString());
     QTY.setText(df.getValueAt(selectedIndex,4).toString());
     MRP.setText(df.getValueAt(selectedIndex,5).toString());;
     WholeSaleRate.setText(df.getValueAt(selectedIndex,6).toString());
     TotalAmount.setText(df.getValueAt(selectedIndex,7).toString());   
    }//GEN-LAST:event_jTable1MouseClicked

    private void JDELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JDELETEActionPerformed
        // TODO add your handling code here:
        
        
    DefaultTableModel df=(DefaultTableModel)jTable1.getModel();
    int selectedIndex=jTable1.getSelectedRow();
    
        
         try {
             int ID=Integer.parseInt(df.getValueAt(selectedIndex, 0).toString());
        int dialogResult=JOptionPane.showConfirmDialog(null,"Want To Delete ","Warning",JOptionPane.YES_NO_OPTION);
        
       if(dialogResult==JOptionPane.YES_NO_OPTION)
       {
       con1=DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql?zeroDateTimeBehavior=convertToNull","root","root@123");
  insert=con1.prepareStatement("delete from Trade.ADDPRODUCt where Id=?");
        insert.setInt(1,ID); 
      insert.executeUpdate();
      JOptionPane.showMessageDialog(this,"Deleted");
         tb_load1();
       ProductName.setText("");
       BrandName.setText("");
       CategoryName.setText("");
       QTY.setText("");
       MRP.setText("");
        WholeSaleRate.setText("");
        TotalAmount.setText("");
        ProductName.requestFocus(); 
      } 
         }
      catch (SQLException ex) {
            Logger.getLogger(ADDPRODUCt.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
    }//GEN-LAST:event_JDELETEActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BrandName;
    private javax.swing.JTextField CategoryName;
    private javax.swing.JButton JADD;
    private javax.swing.JButton JDELETE;
    private javax.swing.JButton JUPDATE;
    private javax.swing.JTextField MRP;
    private javax.swing.JTextField ProductName;
    private javax.swing.JTextField QTY;
    private javax.swing.JTextField TotalAmount;
    private javax.swing.JTextField WholeSaleRate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
